# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-BulkUtil
version:      0.04
version_from: lib/DBIx/BulkUtil.pm
installdirs:  site
requires:
    Carp:                          0
    Cwd:                           0
    DBI:                           0
    IPC::Run:                      0
    Memoize:                       0
    Text::CSV_XS:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
